### ISSUE TITLE
Exception when trying to turn on a light

### ISSUE THREAD

**Issue by indigo-jay** [IndigoDomotics/Hue-Lights-Indigo-plugin#4]
After installing 1.8.10, replacing a 1.7 version from early 2021, I get the following exception when trying to turn on a bulb:

```
   Hue Lights Error                Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 3190, in actionControlDimmerRelay
  File "plugin.py", line 8466, in doOnOff
NameError: global name 'lastUpdated' is not defined
```

**Comment by indigo-jay** [comment]
fixed in 1.9.11 (I think). https://github.com/IndigoDomotics/Hue-Lights-Indigo-plugin/releases/tag/v1.9.11
